# Default initial positions for robot_name's ros2_control fake system

initial_positions:
  joint1: 0.0
  joint2: 0.0
  joint3: 0.0
  joint4: 0.0
  joint5: 0.0
  joint6: 0.0
  joint_gripper_and_left: 0.0